# Generated by Django 5.0.1 on 2024-01-25 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('anime_id', models.CharField(max_length=10, null=True)),
                ('anime_name', models.CharField(max_length=100, null=True)),
                ('anime_release', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnimeDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('anime_id', models.CharField(max_length=10, null=True)),
                ('anime_genre', models.CharField(max_length=50, null=True)),
                ('anime_rating', models.IntegerField(null=True)),
            ],
        ),
    ]
